// Generate sux/src/fns/index.ts — the function manifest — ordered by importance
// (scripts/importance.mjs). Robust to any export-identifier convention: it reads
// each file's `export const X: Fn`. Run: `npm run gen:index`.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { byImportance } from "./importance.mjs";

const FNS = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "fns");
const files = readdirSync(FNS).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && f !== "index.ts" && !f.startsWith("_"));

const entries = [];
for (const f of files) {
	const src = readFileSync(join(FNS, f), "utf8");
	const ident = src.match(/export const (\w+)\s*:\s*Fn\b/)?.[1];
	const name = src.match(/name:\s*"([^"]+)"/)?.[1] ?? f.replace(/\.ts$/, "");
	if (!ident) {
		console.error("SKIP (no `export const X: Fn`):", f);
		continue;
	}
	entries.push({ file: f.replace(/\.ts$/, ""), ident, name });
}
entries.sort((a, b) => byImportance(a.name, b.name));

const imports = entries.map((e) => `import { ${e.ident} } from "./${e.file}";`).join("\n");
const arr = entries.map((e) => `\t${e.ident},`).join("\n");
const out = `// Function manifest — GENERATED by scripts/gen-index.mjs (npm run gen:index).
// Ordered by scripts/importance.mjs so the MCP tools/list surfaces the most
// important tools first. Add a function = create fns/<name>.ts (export const
// <name>: Fn) and re-run the generator.

import type { Fn } from "../registry";
${imports}

export const FUNCTIONS: Fn[] = [
${arr}
];
`;
writeFileSync(join(FNS, "index.ts"), out);
console.log(`Wrote index.ts — ${entries.length} functions, importance-ordered.`);
